### ISSUE TITLE
Exception in thread Wifi

### ISSUE THREAD

**Issue by Wald01991** [sensepost/snoopy-ng#22]
I receive this error when attempting to load the wifi plugin

Exception in thread wifi:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/pi/snoopy-ng/plugins/wifi.py", line 134, in run
    self.iface=mm.enable_monitor_mode(self.iface)
  File "/home/pi/snoopy-ng/includes/monitor_mode.py", line 20, in enable_monitor_mode
    proc  = Popen(['airmon-ng'], stdout=PIPE, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[+] Plugin 'wifi' ran out of time to indicate its ready state, moving on to next plugin.
[+] Done loading plugins, running...

**Comment by glennzw** [comment]
Did the above fix work?
