### ISSUE TITLE
Memory error ? 

### ISSUE THREAD

**Issue by Akumuryu** [sensepost/snoopy-ng#26]
Has anyone seen any memory errors? i see these sometimes when running snoopy either for a few minutes. if it doesn't populate it's usually after snoopy has been running for a longer duration. 

Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 425, in main
    options.key, options.location, options.flush, options.verbose)
  File "/usr/bin/snoopy", line 91, in **init**
    self.go()
  File "/usr/bin/snoopy", line 133, in go
    self.get_data()
  File "/usr/bin/snoopy", line 154, in get_data
    multidata = m.get_data()
  File "/root/snoopy-ng/plugins/wifi.py", line 173, in get_data
    for i in range(self.packet_buffer_size):
MemoryError
Exception in thread wifi:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in **bootstrap_inner
    self.run()
  File "/root/snoopy-ng/plugins/wifi.py", line 134, in run
    self.iface=mm.enable_monitor_mode(self.iface)
  File "/root/snoopy-ng/includes/monitor_mode.py", line 17, in enable_monitor_mode
    disable_monitor_mode()
  File "/root/snoopy-ng/includes/monitor_mode.py", line 39, in disable_monitor_mode
    for device in get_monitor_iface():
  File "/root/snoopy-ng/includes/monitor_mode.py", line 47, in get_monitor_iface
    proc  = Popen(['iwconfig'], stdout=PIPE, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1244, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
MemoryError

**Comment by glennzw** [comment]
I've never seen this error on laptop, BBB, or RPi. I'm thinking that you may not have a suitable monitor mode interface, and snoopy is infinitely looping waiting for one to appear. If you type `airmon-ng` do you see a suitable adapter?
