### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by Akumuryu** [sensepost/snoopy-ng#27]
I have also seen this error sometimes in the same snoopy run when i receive memory errors. 

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/root/snoopy-ng/plugins/wigle.py", line 112, in run
    if 'shun' in locations['error']:
TypeError: string indices must be integers

**Comment by glennzw** [comment]
Not so much a memory error. It happens when Wigle returns bad HTML. Could you give me a sample situation in which this occurred?
