### ISSUE TITLE
Traceback error every 30 to 60 minutes

### ISSUE THREAD

**Issue by JosephGregg** [sensepost/snoopy-ng#43]
This has been going on for a few days now. I was hoping it would go away. Any ideas?

Traceback (most recent call last):
  File "snoopy.py", line 428, in <module>
    main()
  File "snoopy.py", line 425, in main
    options.key, options.location, options.flush, options.verbose)
  File "snoopy.py", line 91, in __init__
    self.go()
  File "snoopy.py", line 133, in go
    self.get_data()
  File "snoopy.py", line 154, in get_data
    multidata = m.get_data()
  File "/root/src/snoopy-ng/plugins/wifi.py", line 178, in get_data
    m.proc_packet(packet)
  File "/root/src/snoopy-ng/plugins/mods80211/wpa.py", line 49, in proc_packet
    self.cp.parse_packet(p)
  File "/usr/lib/pymodules/python2.7/cpyrit/pckttools.py", line 660, in parse_packet
    self._add_keypckt(sta, 0, pckt)
  File "/usr/lib/pymodules/python2.7/cpyrit/pckttools.py", line 564, in _add_keypckt
    self.new_auth_callback((station, auth))
  File "/root/src/snoopy-ng/plugins/mods80211/wpa.py", line 25, in auth_handler
    if auth.station.ap.isCompleted():
AttributeError: 'tuple' object has no attribute 'station'

**Comment by JosephGregg** [comment]
This issue appears to have been related to a faulty alfa wireless card.

**Comment by JosephGregg** [comment]
This issue has returned...guess it wasn't an issue with the wireless card. Sometimes the program goes hours without issue...other times 5 minutes after starting I'm seeing this error:

Traceback (most recent call last):
  File "snoopy.py", line 428, in <module>
    main()
  File "snoopy.py", line 425, in main
    options.key, options.location, options.flush, options.verbose)
  File "snoopy.py", line 91, in __init__
    self.go()
  File "snoopy.py", line 133, in go
    self.get_data()
  File "snoopy.py", line 154, in get_data
    multidata = m.get_data()
  File "/root/src/test2/snoopy-ng/plugins/wifi.py", line 178, in get_data
    m.proc_packet(packet)
  File "/root/src/test2/snoopy-ng/plugins/mods80211/wpa.py", line 49, in proc_packet
    self.cp.parse_packet(p)
  File "/usr/lib/pymodules/python2.7/cpyrit/pckttools.py", line 667, in parse_packet
    self._add_keypckt(sta, 1, pckt)
  File "/usr/lib/pymodules/python2.7/cpyrit/pckttools.py", line 564, in _add_keypckt
    self.new_auth_callback((station, auth))
  File "/root/src/test2/snoopy-ng/plugins/mods80211/wpa.py", line 25, in auth_handler
    if auth.station.ap.isCompleted():
AttributeError: 'tuple' object has no attribute 'station'

**Comment by th36r1m** [comment]
Looks like there might be something wrong with pyrit

**Comment by glennzw** [comment]
I think you're right @th36r1m, something has changed with Pyrit. I use it to capture WPA[2] handshakes For a quick fix whilst I investigate you can disable the WPA capturing sub-plugin by renaming it to have a double underscore at the front:

mv ./snoopy-ng/plugins/mods80211/wpa.py ./snoopy-ng/plugins/mods80211/__wpa.py

**Comment by strasharo** [comment]
Noticed that some folks observed the same issue here:
https://github.com/sensepost/snoopy-ng/issues/73
https://github.com/sensepost/snoopy-ng/issues/58

I'm getting the same issue when running with Alfa Awus036h v5 with Realtek 8187 chipset:

```
[+] Sub-plugin wifi_clients currently observing 58 client devices
Traceback (most recent call last):
  File "/usr/bin/snoopy", line 470, in <module>
    main()
  File "/usr/bin/snoopy", line 461, in main
    options.key, options.location, options.flush, options.verbose)
  File "/usr/bin/snoopy", line 97, in __init__
    self.go_local()
  File "/usr/bin/snoopy", line 142, in go_local
    self.get_data()
  File "/usr/bin/snoopy", line 187, in get_data
    multidata = m.get_data()
  File "/home/b/snoopy-ng/plugins/wifi.py", line 179, in get_data
    m.proc_packet(packet)
  File "/home/b/snoopy-ng/plugins/mods80211/wpa.py", line 49, in proc_packet
    self.cp.parse_packet(p)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 667, in parse_packet
    self._add_keypckt(sta, 1, pckt)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 564, in _add_keypckt
    self.new_auth_callback((station, auth))
  File "/home/b/snoopy-ng/plugins/mods80211/wpa.py", line 25, in auth_handler
    if auth.station.ap.isCompleted():
AttributeError: 'tuple' object has no attribute 'station'
```

When running with TP-Link  TL-WN722N with AR9271using the ath9k driver on the same box, the issue doesn't appear, so I guess it must be specific to the Realtek 8187 chipset and the rtl8187 driver.

**Comment by nik012003** [comment]
Same problem here, I have a TP-Link TL-WN722N with the Atheros chipset.
