### ISSUE TITLE
Confused on how snoopy.db is created

### ISSUE THREAD

**Issue by thesle3p** [sensepost/snoopy-ng#56]
Hi the Readme does not make this clear but how exactly does one create the snoopy.db sqlite file used to store data? I first tried passing it the path to a non existent snoopy.db file in the path I wanted it in hoping it would create such a file but it Crashed, so then I tried creating a empty sqlite database thinking snoopy would populate it with the appropriate tables but I got the same error message.
How am I supposed to create snoopy.db? I encountered this on stock debian and arch linux with SQLAlchemy version 0.7.8  The error message can be found below:

[+] Starting Snoopy with plugins: server
[+] Capturing local only. Saving to 'sqlite:///path/to/snoopy/snoopy-ng/snoopy.db'
Traceback (most recent call last):
  File "./snoopy.py", line 428, in <module>
    main()
  File "./snoopy.py", line 425, in main
    options.key, options.location, options.flush, options.verbose)
  File "./snoopy.py", line 86, in __init__
    if not self.db.dialect.has_table(self.db.connect(), tbl.name):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2013, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 72, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2099, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2073, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1403, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2069, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 708, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1140, in _do_get
    return self._create_connection()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 602, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

**Comment by aiddenkeli** [comment]
You shouldnt try specifying a path to the db file. If you run just the
example in the readme it should create the db file for you.

**Comment by glennzw** [comment]
You need to specify the database format correctly, you're missing one "/".

e.g. 'sqlite:////tmp/snoopy.db'
