### ISSUE TITLE
Kali 2.0 Raspberry Pi install error

### ISSUE THREAD

**Issue by vapor99** [sensepost/snoopy-ng#61]
During the install script it looks like pylibpcap doesn't like something.  Output is below:

[+] Downloading pylibpcap...
Collecting pylibpcap from https://sourceforge.net/projects/pylibpcap/files/latest/download?source=files#egg=pylibpcap
  Downloading https://sourceforge.net/projects/pylibpcap/files/latest/download?source=files (49kB)
    100% |################################| 53kB 52kB/s
Installing collected packages: pylibpcap
  Running setup.py install for pylibpcap
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-qhMZDH/pylibpcap/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-0XZSdQ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building '_pcapmodule' extension
    creating build
    creating build/temp.linux-armv7l-2.7
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSWIG_COBJECT_TYPES -I/usr/include/python2.7 -c pcap.c -o build/temp.linux-armv7l-2.7/pcap.o
    pcap.c: In function 'SWIG_Python_AddErrorMsg':
    pcap.c:853:5: error: format not a string literal and no format arguments [-Werror=format-security]
         PyErr_Format(PyExc_RuntimeError, mesg);
         ^
    cc1: some warnings being treated as errors
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

```
----------------------------------------
```

Command "/usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-qhMZDH/pylibpcap/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-0XZSdQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-qhMZDH/pylibpcap

**Comment by maximcherny** [comment]
apt-get install python-libpcap

**Comment by Hacksawfred3232** [comment]
I have a problem later on when you run it on the raspberry pi. I thought i fixed this!

Traceback (most recent call last):
File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/home/pi/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File "/home/pi/snoopy-ng/plugins/mitmproxy.py", line 17, in <module>
    from includes.mitm import *
  File "/home/pi/snoopy-ng/includes/mitm.py", line 4, in <module>
    from libmproxy import proxy, flow, platform
ImportError: cannot import name platform

**Comment by Hopalonger** [comment]
I Just Rebuilt Snoop-ng For Raspbian and fixed most of the errors. https://github.com/Hopalonger/Snoopy-PI
