### ISSUE TITLE
ImportPlatform error.

### ISSUE THREAD

**Issue by Hacksawfred3232** [sensepost/snoopy-ng#69]
---

/ **)( ( )(  _  )(  _  )(  _ ( \/ )
\** \ )  (  )(_)(  )(_)(  )**_/ \  /
(**_/(_)\_)(_____)(_____)(**)   (**)
                        Version: 2.0
Code:    glenn@sensepost.com // @glennzw
Visit:   www.sensepost.com // @sensepost
License: Non-commercial use

Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/root/Snoopy2.0/snoopy-ng-master/includes/common.py", line 24, in get_plugins
    m = **import**(plug, fromlist="Snoop").Snoop
  File "/root/Snoopy2.0/snoopy-ng-master/plugins/mitmproxy.py", line 17, in <module>
    from includes.mitm import *
  File "/root/Snoopy2.0/snoopy-ng-master/includes/mitm.py", line 4, in <module>
    from libmproxy import proxy, flow, platform
ImportError: cannot import name platform

This is what i keep getting. Anyway to fix?

**Comment by Hacksawfred3232** [comment]
NVM. Found the fix. Naming it snoopy2.0 Caused to bug out.

EDIT: New soulotuin, Remove the MITM.py and MITMproxy.py files because on the raspberry pi version 1 b+, they are incompablte.
