### ISSUE TITLE
starting snoopy locally received exception

### ISSUE THREAD

**Issue by Ghostthirsty** [sensepost/snoopy-ng#70]
Using the snoopy -v -m server  command I received the following warning. I am not sure what is happening here

[WARNING] Drone (-d) or locaion (-l) not specified. May not be required by the plugins you're using.
[+] Starting Snoopy with plugins: server
[+] Capturing local only. Saving to 'sqlite:///snoopy.db'
[+] Waiting for plugin 'server' to indicate it's ready
[+] Plugin 'server' has indicated it's ready.
[+] Running webserver on '0.0.0.0:9001'
[+] Done loading plugins, running...
Exception in thread server:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/root/snoopy-ng/plugins/server.py", line 63, in run
    webserver.run_webserver(self.port,self.ip,self.cert,self.cert_key,self.db)
  File "/root/snoopy-ng/includes/webserver.py", line 151, in run_webserver
    auth_ = auth(rawdb=_db)
  File "/root/snoopy-ng/includes/auth_handler.py", line 46, in __init**
    self.db.create(drone_tbl_def)
  File "<string>", line 2, in create
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/deprecations.py", line 106, in warned
    return fn(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/interfaces.py", line 859, in create
    raise NotImplementedError()
NotImplementedError

**Comment by maximcherny** [comment]
Check out #10
