### ISSUE TITLE
Wigle plugin Error

### ISSUE THREAD

**Issue by ProGamerGov** [sensepost/snoopy-ng#72]
```
[WARNING] Drone (-d) or locaion (-l) not specified. May not be required by the plugins you're using.
[+] Starting Snoopy with plugins: wigle
[+] Capturing local only. Saving to 'sqlite:///snoopy.db'
[+] Waiting for plugin 'wigle' to indicate it's ready
[+] Plugin 'wigle' has indicated it's ready.
[+] Done loading plugins, running...
Exception in thread wigle:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/snoopy-ng/plugins/wigle.py", line 112, in run
    if 'shun' in locations['error']:
TypeError: string indices must be integers

```

```
[+] Starting Snoopy with plugins: wigle
[+] Capturing local only. Saving to 'sqlite:///snoopy.db'
[+] Waiting for plugin 'wigle' to indicate it's ready
[+] Plugin 'wigle' has indicated it's ready.
[+] Done loading plugins, running...
Exception in thread wigle:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/snoopy-ng/plugins/wigle.py", line 112, in run
    if 'shun' in locations['error']:
TypeError: string indices must be integers
```

It was working really well until this error came along. Any help fixing it would be appreciated.

I am not sure I should just let it continue on and it will work, or whether or not i have to fix this error for it to work.

A "snoopydb.journal" file seems to be created and removed constantly inside the snoopy folder.

**Comment by ProGamerGov** [comment]
```
2016-02-18 15:33:01 [35m+[32m snoopy: Starting Snoopy with plugins: [37mwigle[32m
2016-02-18 15:33:01 [35m+[32m snoopy: Capturing local only. Saving to 'sqlite:///snoopy.db'
2016-02-18 15:33:04 [35m+[32m snoopy: Waiting for plugin 'wigle' to indicate it's ready
2016-02-18 15:33:04 D wigle_api.py: [+] Logging into wigle with Username:Password via proxy '{'http': None, 'https': None}'
2016-02-18 15:33:04 [35m+[32m snoopy: Plugin 'wigle' has indicated it's ready.
2016-02-18 15:33:04 [35m+[32m snoopy: Done loading plugins, running...
2016-02-18 15:33:04 D wigle.py: SSID lookup queue has 3022 SSIDs to query
2016-02-18 15:33:05 D wigle_api.py: Successfully logged in with credentials Username:Password.
2016-02-18 15:33:05 D wigle.py: Looking up bahay (<type 'unicode'>)
2016-02-18 15:33:20 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:33:35 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:33:50 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:34:06 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:34:21 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:34:37 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:34:52 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:35:08 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:35:23 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:35:39 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:35:54 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:36:09 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:36:24 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:36:39 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:36:54 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:37:09 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:37:25 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:37:41 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:37:57 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:38:13 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:38:28 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:38:44 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:38:59 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:39:14 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:39:29 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:39:44 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:40:00 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:40:15 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:40:31 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:40:46 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:41:01 D wigle.py: SSID lookup queue has 3021 SSIDs to query
2016-02-18 15:41:17 D wigle.py: SSID lookup queue has 3021 SSIDs to query

```

It occurs to me after reviewing the log files that Snoopy-ng produces, that I may have hit my daily Wigle limit. Though the only way to test this, is to wait 24 hours before trying again.  

Looking into my database, it would seem to point as well to hitting my Wigle daily limit.

**Comment by ProGamerGov** [comment]
I can confirm this error is caused by hitting the daily download limit for the Wigle database.
