### ISSUE TITLE
Snoopy-ng's Wifi module stops working after a period of time

### ISSUE THREAD

**Issue by ProGamerGov** [sensepost/snoopy-ng#73]
```
[+] Sub-plugin wifi_aps currently observing 34 Access Points
Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 425, in main
    options.key, options.location, options.flush, options.verbose)
  File "/usr/bin/snoopy", line 91, in __init__
    self.go()
  File "/usr/bin/snoopy", line 133, in go
    self.get_data()
  File "/usr/bin/snoopy", line 154, in get_data
    multidata = m.get_data()
  File "/root/snoopy-ng/plugins/wifi.py", line 178, in get_data
    m.proc_packet(packet)
  File "/root/snoopy-ng/plugins/mods80211/wpa.py", line 49, in proc_packet
    self.cp.parse_packet(p)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 673, in parse_packet
    self._add_keypckt(sta, 2, pckt)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 564, in _add_keypckt
    self.new_auth_callback((station, auth))
  File "/root/snoopy-ng/plugins/mods80211/wpa.py", line 25, in auth_handler
    if auth.station.ap.isCompleted():
AttributeError: 'tuple' object has no attribute 'station'
[+] Sub-plugin wifi_aps currently observing 34 Access Points
Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 425, in main
    options.key, options.location, options.flush, options.verbose)
  File "/usr/bin/snoopy", line 91, in __init__
    self.go()
  File "/usr/bin/snoopy", line 133, in go
    self.get_data()
  File "/usr/bin/snoopy", line 154, in get_data
    multidata = m.get_data()
  File "/root/snoopy-ng/plugins/wifi.py", line 178, in get_data
    m.proc_packet(packet)
  File "/root/snoopy-ng/plugins/mods80211/wpa.py", line 49, in proc_packet
    self.cp.parse_packet(p)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 673, in parse_packet
    self._add_keypckt(sta, 2, pckt)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 564, in _add_keypckt
    self.new_auth_callback((station, auth))
  File "/root/snoopy-ng/plugins/mods80211/wpa.py", line 25, in auth_handler
    if auth.station.ap.isCompleted():
AttributeError: 'tuple' object has no attribute 'station'
```

```

[+] Sub-plugin wifi_clients currently observing 163 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 169 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 191 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 193 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 196 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 196 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 186 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 187 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 189 client devices
[+] Sub-plugin wifi_aps currently observing 30 Access Points
[+] Sub-plugin wifi_clients currently observing 186 client devices
Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 425, in main
    options.key, options.location, options.flush, options.verbose)
  File "/usr/bin/snoopy", line 91, in __init__
    self.go()
  File "/usr/bin/snoopy", line 133, in go
    self.get_data()
  File "/usr/bin/snoopy", line 154, in get_data
    multidata = m.get_data()
  File "/root/snoopy-ng/plugins/wifi.py", line 178, in get_data
    m.proc_packet(packet)
  File "/root/snoopy-ng/plugins/mods80211/wpa.py", line 49, in proc_packet
    self.cp.parse_packet(p)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 667, in parse_packet
    self._add_keypckt(sta, 1, pckt)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 564, in _add_keypckt
    self.new_auth_callback((station, auth))
  File "/root/snoopy-ng/plugins/mods80211/wpa.py", line 25, in auth_handler
    if auth.station.ap.isCompleted():
AttributeError: 'tuple' object has no attribute 'station'
```

Not sure why or how this occurs, but it makes it impossible to run Snoopy-ng for an extended period of time.

**Comment by ProGamerGov** [comment]
The snoopy.log file had this from when the error occurs: 

```
2016-02-18 15:46:48 [35m+[32m snoopy: Starting Snoopy with plugins: [37mwifi[32m
2016-02-18 15:46:48 [35m+[32m snoopy: Capturing local only. Saving to 'sqlite:///snoopy.db'
2016-02-18 15:46:49 [35m+[32m snoopy: Waiting for plugin 'wifi' to indicate it's ready
2016-02-18 15:46:49 [35m+[32m wifi.py: No interface specified. Will sniff *all* interfaces.
2016-02-18 15:46:49 [35m+[32m snoopy: Plugin 'wifi' has indicated it's ready.
2016-02-18 15:46:49 [35m+[32m snoopy: Done loading plugins, running...
2016-02-18 15:46:51 [35m+[32m wifi_aps.py: Sub-plugin [37mwifi_aps[32m currently observing [37m2[32m Access Points
2016-02-18 15:46:52 [35m+[32m wifi_clients.py: Sub-plugin [37mwifi_clients[32m currently observing [37m1[32m client devices
2016-02-18 15:47:11 [35m+[32m wifi_aps.py: Sub-plugin [37mwifi_aps[32m currently observing [37m3[32m Access Points
2016-02-18 15:47:14 [35m+[32m wifi_clients.py: Sub-plugin [37mwifi_clients[32m currently observing [37m1[32m client devices
2016-02-18 15:47:32 [35m+[32m wifi_aps.py: Sub-plugin [37mwifi_aps[32m currently observing [37m3[32m Access Points
2016-02-18 15:47:35 [35m+[32m wifi_clients.py: Sub-plugin [37mwifi_clients[32m currently observing [37m2[32m client devices
2016-02-18 15:47:53 [35m+[32m wifi_aps.py: Sub-plugin [37mwifi_aps[32m currently observing [37m3[32m Access Points
2016-02-18 15:47:58 [35m+[32m wifi_clients.py: Sub-plugin [37mwifi_clients[32m currently observing [37m4[32m client devices
```

Any help on solving this strange issue would be appreciated.

**Comment by strasharo** [comment]
What's the wireless chipset that you're using?
