### ISSUE TITLE
snoopy_auth won't run

### ISSUE THREAD

**Issue by daveymate** [sensepost/snoopy-ng#75]
Hi,

I'm running snoopy on a Kali 2 box, fresh install. I also have a raspberry pi running snoopy fine as a drone. I can't set up auth or run server using 'snoopy --plugin server'

results of snoopy_auth -c CREATe myDrone

Traceback (most recent call last):
  File "/usr/bin/snoopy_auth", line 169, in <module>
    auth_ = auth(args.dbms)
  File "/usr/bin/snoopy_auth", line 46, in **init**
    self.db.create(drone_tbl_def)
  File "<string>", line 2, in create
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/deprecations.py", line 106, in warned
    return fn(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/interfaces.py", line 859, in create
    raise NotImplementedError()
NotImplementedError

Results of 'snoopy --plugin server
# snoopy --plugin server

---

/ **)( ( )(  _  )(  _  )(  _ ( \/ )
\** \ )  (  )(_)(  )(_)(  )**_/ \  /
(**_/(_)\_)(_____)(_____)(**)   (**)
                        Version: 2.0
Code:    glenn@sensepost.com // @glennzw
Visit:   www.sensepost.com // @sensepost
License: Non-commercial use

[WARNING] Drone (-d) or locaion (-l) not specified. May not be required by the plugins you're using.
[+] Starting Snoopy with plugins: server
[+] Capturing local only. Saving to 'sqlite:///snoopy.db'
[+] Waiting for plugin 'server' to indicate it's ready
[+] Running webserver on '0.0.0.0:9001'
[+] Plugin 'server' has indicated it's ready.
[+] Done loading plugins, running...
Exception in thread server:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/root/snoopy-ng/plugins/server.py", line 63, in run
    webserver.run_webserver(self.port,self.ip,self.cert,self.cert_key,self.db)
  File "/root/snoopy-ng/includes/webserver.py", line 151, in run_webserver
    auth_ = auth(rawdb=_db)
  File "/root/snoopy-ng/includes/auth_handler.py", line 46, in __init**
    self.db.create(drone_tbl_def)
  File "<string>", line 2, in create
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/deprecations.py", line 106, in warned
    return fn(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/interfaces.py", line 859, in create
    raise NotImplementedError()
NotImplementedError

Thanks in advance for any help anyone can provide.

**Comment by daveymate** [comment]
Fixed this on my own, found a previous issue, I thought I looked through everything. 
easy_install sqlite7.8 did it. Thanks for an awesome tool!

**Comment by gunwi** [comment]
Thank you - i will try it on my system asap ;-)

**Comment by jl2035** [comment]
How do you do "easy_install sqlite7.8"? That command always fails for me, even if I remove "7.8".
