### ISSUE TITLE
six.moves issue, ubuntu 16.04

### ISSUE THREAD

**Issue by alijnclarke** [sensepost/snoopy-ng#77]
So i've just done a fresh install of snoopy on Ubuntu 16.04 and i'm getting the following when trying to execute the snoopy command.

Any ideas on the fix? six.moves range seems to exist in the python command line.

 Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/home/ali/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = **import**(plug, fromlist="Snoop").Snoop
  File "/home/ali/snoopy-ng/plugins/mitmproxy.py", line 17, in <module>
    from includes.mitm import *
  File "/home/ali/snoopy-ng/includes/mitm.py", line 4, in <module>
    from libmproxy import proxy, flow, platform
  File "/usr/lib/python2.7/dist-packages/libmproxy/proxy/**init**.py", line 3, in <module>
    from .server import ProxyServer, DummyServer
  File "/usr/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 8, in <module>
    from netlib import tcp
  File "/usr/lib/python2.7/dist-packages/netlib/tcp.py", line 11, in <module>
    from six.moves import range
ImportError: cannot import name range

**Comment by NoobieDog** [comment]
I beieve you have to disable the mitm.py and rogueap.py plugins by renaming
them to something else or deleting them.

I understand this to be an error with the libpcap python libs

Stu

**Comment by alijnclarke** [comment]
@NoobieDog ace that fixed it, seems to be quite a few issues with the libpcap stuff.

Shame there isnt much activity here anymore

**Comment by TheRealXaiL** [comment]
Please see my [gist](https://gist.github.com/JosephGregg/c31a4b0148240547d54ddaea19bf8d35)...it may help you.

**Comment by UnknownBean** [comment]
@NoobieDog that didn't work for me i have the same error message but i only had mitm.py not the other one. any other ideas
