### ISSUE TITLE
plz help i got snoopy to install but server wont start

### ISSUE THREAD

**Issue by ErinBejtaa** [sensepost/snoopy-ng#85]
root@KS-ThinkPad-T410:~/snoopy-ng# snoopy_auth --create myDrone
[+] Creating new Snoopy server sync account
[+] Key for 'myDrone' is 'EVIAAI9RPWDX2RZ'
[+] Use this value in client mode to sync data to a remote server.
root@KS-ThinkPad-T410:~/snoopy-ng# snoopy -v -m server
 ___  _  _  _____  _____  ____  _  _
/ __)( \( )(  _  )(  _  )(  _ \( \/ )
\__ \ )  (  )(_)(  )(_)(  )___/ \  /
(___/(_)\_)(_____)(_____)(__)   (__)
                        Version: 2.0
Code:	 glenn@sensepost.com // @glennzw
Visit:	 www.sensepost.com // @sensepost
License: Non-commercial use

Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/home/fsociety/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File "/home/fsociety/snoopy-ng/plugins/mitmproxy.py", line 17, in <module>
    from includes.mitm import *
  File "/home/fsociety/snoopy-ng/includes/mitm.py", line 4, in <module>
    from libmproxy import proxy, flow, platform
ImportError: No module named libmproxy
root@KS-ThinkPad-T410:~/snoopy-ng#

**Comment by ErinBejtaa** [comment]
fixed it
