### ISSUE TITLE
unable to import range

### ISSUE THREAD

**Issue by ErinBejtaa** [sensepost/snoopy-ng#86]
Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/home/fsociety/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File "/home/fsociety/snoopy-ng/plugins/mitmproxy.py", line 17, in <module>
    from includes.mitm import *
  File "/home/fsociety/snoopy-ng/includes/mitm.py", line 4, in <module>
    from mitmproxy import proxy, flow, platform
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/__init__.py", line 3, in <module>
    from .config import ProxyConfig
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/config.py", line 15, in <module>
    from netlib import tcp
  File "/usr/lib/python2.7/dist-packages/netlib/tcp.py", line 15, in <module>
    from six.moves import range
ImportError: cannot import name range

**Comment by ErinBejtaa** [comment]
found a fix 
just write on terminal 
rm -r snoopy-ng/plugins/mitmproxy.py
