### ISSUE TITLE
No module named libmproxy

### ISSUE THREAD

**Issue by AnaasN** [sensepost/snoopy-ng#91]
Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/root/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File "/root/snoopy-ng/plugins/mitmproxy.py", line 17, in <module>
    from includes.mitm import *
  File "/root/snoopy-ng/includes/mitm.py", line 4, in <module>
    from libmproxy import proxy, flow, platform
**ImportError: No module named libmproxy**

This error occurs when issuing the commands;
"snoopy --plugin server"
"snoopy --drone --location"
not sure how to resolve, Ive tried updating mitmroxy but still nothing.

**Comment by ErinBejta** [comment]
nano snoopy-ng/includes/mitm.py           change from libmproxy to mitmproxy
rm -r snoopy-ng/plugins/mitmproxy.py 
snoopy should run fine

**Comment by ErinBejta** [comment]
or checkout my repo 
git clone https://github.com/ErinBejta/snoopy-ng
cd snoopy-ng
bash install.sh
should work if you're running Kali

**Comment by AnaasN** [comment]
Installed your version and I got this error:
```
Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File "/root/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File "/root/snoopy-ng/plugins/server.py", line 17, in <module>
    from includes import webserver
  File "/root/snoopy-ng/includes/webserver.py", line 8, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 15, in <module>
    from cryptography import utils, x509
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/base.py", line 15, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 22, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 15, in <module>
    from six.moves import urllib_parse
**ImportError: cannot import name urllib_parse**

```
Reinstalled libpython2.7 but still same error.

**Comment by BlyBergen** [comment]
Nobody's posted here in a year and but I really needed this working for a school project, so here's my duct tape fix. I did exactly what ErinBejta described in her solution and saw the same error that AnaasN got.  I went into that "usr/lib/python2.7/dist-packages/cryptography/x509/general_name.py" and replaced the call to six.moves
```
from six.moves import urllib_parse
```
with this:

```
import six

if six.PY3:

	import urllib.parse

else:

	import urllib
	import urlparse
```

I haven't tested it thoroughly, but it's letting me do what I need to and snoopy is running smoothly for me, so I'm posting it here.  I'm well aware that this could lead to issues down the road, but I haven't encountered any yet, so I'll cross that bridge once I get to it.

**Comment by An0nJ** [comment]
I love U   BlyBergen   I really really really love,
where u been all this time,  :)
                                                 ;)

**Comment by gumpetung** [comment]
BlyBergen is a hero

**Comment by gumpetung** [comment]
@BlyBergen you are a hero. Spend hours searching for this.
